// cuando todo funcioa okey
try {
  console.log(10 / 2)
} catch (error) {
  console.error("error detectacdo", error)
}
// cuando existe error en el codigo
try {
  console.log(hola / hola2)
} catch (error) {
  console.error("error detectacdo", error)
}